<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.rednorte</groupId>
    <artifactId>salud-rednorte-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging> <modules>
        <module>api-gateway</module>
        <module>bff</module>
        <module>waitlist-service</module>
        <module>AutoReasign-Service</module>
        <module>patient-portal-service</module>
    </modules>

    </project>