<project>
    <modelVersion>4.0.0</modelVersion>
    <groupId>com.rednorte</groupId>
    <artifactId>salud-rednorte-parent</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging> 
    <modules>
        <module>ApiGateway</module>
        <module>BFF</module>
        <module>waitlist-service</module>
        <module>AutoReasign-Service</module>
        <module>Patient-Portal</module>
        <module>security</module>
    </modules>

    <build>
        <plugins>
            <plugin>
                <groupId>org.jacoco</groupId>
                <artifactId>jacoco-maven-plugin</artifactId>
                <version>0.8.12</version> <configuration>
                    <excludes>
                        <exclude>**/dto/**</exclude>
                        <exclude>**/dtos/**</exclude>
                        <exclude>**/model/**</exclude>
                        <exclude>**/entities/**</exclude>
                        <exclude>**/config/**</exclude>
                        <exclude>**/*Application.class</exclude>
                    </excludes>
                </configuration>
                <executions>
                    <execution>
                        <goals>
                            <goal>prepare-agent</goal>
                        </goals>
                    </execution>
                    <execution>
                        <id>report</id>
                        <phase>test</phase>
                        <goals>
                            <goal>report</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>

</project>
    