server.port=8081
spring.application.name=waitlist-service

spring.datasource.url=jdbc:mysql://localhost:3306/db_waitlist?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=rootpassword
spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

resilience4j.circuitbreaker.instances.waitlistCB.sliding-window-size=8
resilience4j.circuitbreaker.instances.waitlistCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.waitlistCB.wait-duration-in-open-state=12s

springdoc.swagger-ui.config-url=/v3/api-docs/swagger-config
springdoc.api-docs.path=/v3/api-docs