server:
  port: 8084

spring:
  application:
    name: patient-portal-service
  datasource:
    url: jdbc:mysql://localhost:3306/db_patient_portal?useSSL=false&serverTimezone=UTC
    username: root
    password: rootpassword

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

resilience4j:
  circuitbreaker:
    instances:
      portalPacienteCB:
        slidingWindowSize: 10
        failureRateThreshold: 40
        waitDurationInOpenState: 10s

springdoc:
  api-docs:
    server:
      servlet-context-path: /