spring.application.name=BFF

resilience4j.circuitbreaker.instances.dashboardCB.sliding-window-size=10
resilience4j.circuitbreaker.instances.dashboardCB.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.dashboardCB.wait-duration-in-open-state=15s